version: 2
jobs:
  build-front:
    docker:
      - image: circleci/node:latest
    working_directory: $CIRCLE_WORKING_DIRECTORY/client
    steps:
      - checkout
      - run: npm run build
  test-front:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "test more"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-front
      - test-front