version: 2
jobs:
  build-front:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm run build
  test-front:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "test again"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-front
      - test-front
